CREATE TABLE Listing(
	ListingId INT NOT NULL AUTO_INCREMENT,
	Address VARCHAR(128) NOT NULL,
	Description VARCHAR(128) NOT NULL,
	Price VARCHAR(16) NOT NULL,
	DateSubmitted DATETIME NOT NULL,
	PRIMARY KEY (ListingId)
);